### ISSUE TITLE
Support for Redux

### ISSUE THREAD

**Issue by devWaleed** [ricardoemerson/create-react-tsx-component#8]
Hey, great package here!

Can you also add support for redux-connect api based components ?

**Comment by ricardoemerson** [comment]
Hi, thanks for using the extension.

In this extension I tried to be as simple as possible and bring a more general view so that everyone can use it.

In the case of Redux, I believe that there would have to be a specific extension to create its elements.

I am not using redux lately, but I am using React contexts. In this case I use snippets that I created to create contexts and hooks in my projects.

In the case of Next JS pages, I create only the function and if I need to use SSR for example, I use a snippet that I created for this purpose.

So, I suggest that you create a snippet of vscode so that it can meet this specificity.
